---

  - name: Setup Webservers
    hosts: localhost
    connection: local
    gather_facts: yes
    vars_files:
      - ../vars/public.yaml
      - ../vars/secret.yaml

    tasks:

    - name: ensure Webserver 01 is running
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{ target_aws_region }}"
        key_name: "{{ ssh_key_pair }}"
        image: "{{ web_ami_id }}"
        instance_type: "{{ web_instance_type }}"
        group_id: "{{ sg_linux_hosts_out.group_id }}"
        vpc_subnet_id: "{{ int_subnet_id }}"
        private_ip: "{{ web_ip_01 }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: "{{ env }} _ Webserver 01"
        instance_tags:
          Name: "{{ env }} _ Webserver 01"
        user_data: "{{ lookup('template', '../templates/userdata_webserver1.j2') }}"
      register: ec2_web01_result

    - name: ensure Webserver 02 is running
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{ target_aws_region }}"
        key_name: "{{ ssh_key_pair }}"
        image: "{{ web_ami_id }}"
        instance_type: "{{ web_instance_type }}"
        group_id: "{{ sg_linux_hosts_out.group_id }}"
        vpc_subnet_id: "{{ int_subnet_id }}"
        private_ip: "{{ web_ip_02 }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: "{{ env }} _ Webserver 02"
        instance_tags:
          Name: "{{ env }} _ Webserver 02"
        user_data: "{{ lookup('template', '../templates/userdata_webserver2.j2') }}"
      register: ec2_web02_result

    - name: ensure Webserver 03 is running
      ec2:
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        region: "{{ target_aws_region }}"
        key_name: "{{ ssh_key_pair }}"
        image: "{{ web_ami_id }}"
        instance_type: "{{ web_instance_type }}"
        group_id: "{{ sg_linux_hosts_out.group_id }}"
        vpc_subnet_id: "{{ int_subnet_id }}"
        private_ip: "{{ web_ip_03 }}"
        wait: yes
        wait_timeout: 500
        exact_count: 1
        count_tag:
          Name: "{{ env }} _ Webserver 03"
        instance_tags:
          Name: "{{ env }} _ Webserver 03"
        user_data: "{{ lookup('template', '../templates/userdata_webserver3.j2') }}"
      register: ec2_web03_result